AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambdas for HW3
Resources:
  Lambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos-2
      Handler: search-photos.lambda_handler
      Runtime: python3.7
      CodeUri: ./search-photos.py
      Description: 'Lambda function to search photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::645074619784:role/service-role/search-photos-role-udo1xveo'
      Environment:
        Variables:
          REGION: us-east-1
  Lambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos-2
      Handler: index-photos.lambda_handler
      Runtime: python3.7
      CodeUri: ./index-photos.py
      Description: 'Lambda function to index photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::645074619784:role/service-role/index-photos-role-jjbi22ef'
      Environment:
        Variables:
          REGION: us-east-1
  Lambda3:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: get-photo-request-2
      Handler: get-photo-request.lambda_handler
      Runtime: python3.7
      CodeUri: ./get-photo-request.py
      Description: 'Lambda function to handle queries'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::645074619784:role/service-role/get-photo-request-role-x2ba4yt6'
      Environment:
        Variables:
          REGION: us-east-1
  Lambda4:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: upload-photos-2
      Handler: upload-photos.lambda_handler
      Runtime: javascript
      CodeUri: ./upload-photos.js
      Description: 'Lambda function to handle uploads'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::645074619784:role/service-role/upload-photos-role-kyd8bvna'
      Environment:
        Variables:
          REGION: us-east-1