AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambdas for HW3
Resources:
  Lambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./src/search-photos
      Description: 'Lambda function to search photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::645074619784:role/service-role/search-photos-role-udo1xveo'
      Environment:
        Variables:
          REGION: us-east-1
  Lambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./src/index-photos
      Description: 'Lambda function to index photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::645074619784:role/service-role/index-photos-role-jjbi22ef'
      Environment:
        Variables:
          REGION: us-east-1